commerce/auctions/urls.py
from django.urls import path

from . import views

app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/categories/urls.py
from django.urls import path

from . import views

app_name = "categories"
urlpatterns = [
    path("", views.Categories, name="index"),
    path("", views.CategoryView, name="catView"),
    path("<str:categoryName>", views.CategoryView, name="catView")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("create/", include("createList.urls")),
    path("categories/", include("categories.urls")),
    path("watchlist/", include("watchlist.urls")),
    path("listings/", include("listings.urls"))
]

commerce/createList/urls.py
from django.urls import path

from . import views

app_name = "creation"
urlpatterns = [
    path("", views.createListing, name="create"),
    path("<int:idNo>", views.createListing, name="create")
]

commerce/listings/urls.py
from django.urls import path

from . import views
# IT IS IMPORT TO REMEMBER THAT URL WITH ARGUMENTS CAN NEVER BE IDENTICAL. EVEN IF NAME ATTR IS DIFFERENT
app_name = "listings"
urlpatterns = [
    path("", views.listingsView, name="index"),
    path('<int:idNo>', views.listingsView, name="index"),

    path("", views.postComment, name="comm"),
    path("post_comment",views.postComment,name="comm"),

    path("", views.addToWatchList, name="add"),
    path("add_to_list",views.addToWatchList,name="add"),

    path("", views.DelFromWatchList, name="del"),
    path("remove_to_list",views.DelFromWatchList,name="del"),

    path("", views.createBid, name="bid"),
    path("submit_bid",views.createBid,name="bid"),

    path("", views.closeListing, name="close"),
    path("close_listing",views.closeListing,name="close")
]

commerce/watchlist/urls.py
from django.urls import path

from . import views

app_name = "watchlist"
urlpatterns = [
    path("", views.watchlistView, name="index"),
    path("<int:idNo>", views.watchlistView, name="index"),
    path("None", views.watchlistView, name="noUser") # for cases when no user is logged
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f"{self.id}"

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import get_user
from watchlist.models import watcherList
from .models import User
from django.contrib.auth.decorators import login_required
from createList.models import Listing
from .models import User


def index(request):
    idNo = get_user(request).id
    user_code = User.objects.get(id=idNo)
    try:
        watchedItems = watcherList.objects.filter(watchedBy=user_code).count()
    except:
        watchedItems= 0
    return render(request, "auctions/index.html",{
        "lists":Listing.objects.all(),"watchedItems":watchedItems})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index",))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
{% for entry in lists %}
<hr>
<!---->

    <div style="width: 100%; display: table; background-color:#ffe6ff;">
        <div style="display: table-row; padding-top: 20px;">

            <div style="width: 350px; display: table-cell;">
                <!--brings me to listings page with Listing ID#-->
                <a href="{% url 'listings:index'%}{{ entry.id }}">
                   <img style="margin-left:  30px;" src="{{ entry.url }}"
                        alt="image could not load" width="300" height="200"></a>
            </div>

                <div style="display: table-cell; padding-top: 20px;padding-left: 80px;">
                    <p><b>{{ entry.title }}</b></p>
                    <p><b>Price: ${{ entry.bid | floatformat:2}}</b></p>
                    <p>{{ entry.description }}</p>
                    <p class="text-muted">{{ entry.createDateTime }}</p>
                </div>
        </div>
    </div>

{% empty %}
    <strong>NO LISTINGS</strong>

{% endfor %}
<div hidden>
    {% block notifCount %}
        {{ watchedItems }}
    {% endblock %}
</div>
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:index' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'watchlist:index' %}{{ user.id }}">Watchlist</a>
                <span style="position: relative;padding: 2px 5px;border-radius: 20%;bottom: 35px;
         background: darkblue; left: 85px; color: white;" class="counter">
                    {% block notifCount %}{% endblock %}</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'creation:create'%}{{ user.id }}">Create Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}