commerce/auctions/urls.py
from django.urls import path

from . import views

app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("create/", include("createList.urls")),
    path("categories/", include("categories.urls")),
    path("watchlist/", include("watchlist.urls")),
    path("listings/", include("listings.urls"))
]

commerce/listings/urls.py
from django.urls import path

from . import views
# IT IS IMPORT TO REMEMBER THAT URL WITH ARGUMENTS CAN NEVER BE IDENTICAL. EVEN IF NAME ATTR IS DIFFERENT
app_name = "listings"
urlpatterns = [
    path("", views.listingsView, name="index"),
    path('<int:idNo>', views.listingsView, name="index"),

    path("", views.postComment, name="comm"),
    path("post_comment",views.postComment,name="comm"),

    path("", views.addToWatchList, name="add"),
    path("add_to_list",views.addToWatchList,name="add"),

    path("", views.DelFromWatchList, name="del"),
    path("remove_to_list",views.DelFromWatchList,name="del"),

    path("", views.createBid, name="bid"),
    path("submit_bid",views.createBid,name="bid"),

    path("", views.closeListing, name="close"),
    path("close_listing",views.closeListing,name="close")
]

commerce/listings/models.py
from django.db import models
from auctions.models import User
from datetime import datetime
from django.utils import timezone
from createList.models import Listing
# Create your models here.


class Bids(models.Model):
    listingID = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bidList", default=1)
    bidBy = models.ForeignKey(User, on_delete=models.CASCADE,related_name="bidUser", default=1)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    datetimeOfBid = models.DateTimeField()


class Comment(models.Model):
    listingID = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="commentList", default=1)
    commentBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentUser", default=1)
    commentMade = models.CharField(max_length=500)
    datetimeOfComment = models.DateTimeField()


# THIS MODEL IS FOR STORING HISTORICAL DATA FOR CLOSED POSTS

class hist_lists(models.Model):
    listingID = models.CharField(max_length=40, primary_key=True)
    startingBid = models.FloatField(max_length=40)
    finalBid = models.FloatField(max_length=40)
    finalBidBy = models.CharField(max_length=40)
    listBy = models.CharField(max_length=40)
    closedDateTime = models.DateTimeField()


def __str__(self):
    return f"ID:{self.id},List ID:{self.listingID},Bid By: {self.bidBy}, Amount:{self.amount}"

commerce/listings/views.py
from django.shortcuts import render
from createList.models import Listing
from auctions.models import User
from watchlist.models import watcherList
from .models import Bids, hist_lists, Comment
from django.db.models import Max
from django.contrib import messages
from django.contrib.auth import get_user
from datetime import datetime
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='/admin')
def postComment(request):
        userCommText = request.POST['userComment']
        postID = request.POST['postingID']


        listing = Listing.objects.get(id=postID)
        userPostingID = get_user(request).id
        userPosting = User.objects.get(id=userPostingID)
        cDate = datetime.now()
        Comment.objects.create(listingID=listing, commentBy=userPosting, commentMade=userCommText,
                               datetimeOfComment=cDate)
        return HttpResponseRedirect(reverse("listings:index",args=(postID,)))


@login_required(login_url='/admin')
def createBid(request):
    fromForm = request.POST['bidAmt']
    idNum = request.POST['listingID']
    bid = float(fromForm)
    listId = str(idNum)

    listIdNum = Listing.objects.get(id=listId)  # list object
    userId = get_user(request).id
    UserID = User.objects.get(id=userId)  # user object

    maxBid = listIdNum.bid
    startBid = listIdNum.startingBid

    # validation for bid amount
    if UserID != listIdNum.userID:
        if bid >= startBid and bid > maxBid:
            # checks if user has current bid on item
            if Bids.objects.filter(listingID=listIdNum, bidBy=UserID).exists():
                curr_bid = Bids.objects.get(listingID=listIdNum, bidBy=UserID)
                curr_bid.amount = bid
                curr_bid.save()
                # updates current listing with new bid amount
                listIdNum.bid = bid
                listIdNum.save()
                listIdNum.currBidBy = UserID
                listIdNum.save()
                messages.info(request, "Your bid has been placed.")
                return HttpResponseRedirect(reverse("listings:index", args=(listId,)))
            else:
                # gets listing from db based on ID number
                cDate = datetime.now()
                Bids.objects.create(listingID=listIdNum, bidBy=UserID, amount=bid,datetimeOfBid=cDate)

                # updates current listing with new bid amount
                listIdNum.bid = bid
                listIdNum.save()
                listIdNum.currBidBy = UserID
                listIdNum.save()
                messages.info(request, "Your bid has been placed.")
                return HttpResponseRedirect(reverse("listings:index", args=(listId,)))
        else:
            messages.error(request, "This bid cannot be placed. Please adjust bid amount.")
            return HttpResponseRedirect(reverse("listings:index", args=(listId,)))
    else:
        messages.error(request, "Cannot bid on own listing.")
        return HttpResponseRedirect(reverse("listings:index", args=(listId,)))


# This function lists full details of an item. it will search for item from watchList table automatically
# if no item is found null is sent to template and Button becomes "Add to list"
# if item is found then it is sent to template and Button becomes "Remove to list"

@login_required(login_url='/admin')
def listingsView(request, idNo):
    userID = get_user(request).id
# checks user won listing or not
    if not hist_lists.objects.filter(finalBidBy=userID, listingID=idNo).exists():

        # checks if listing ID in URL exists. i.e. listing is open
        if Listing.objects.filter(id=idNo).exists():
            listing = Listing.objects.get(id=idNo)

            user = User.objects.get(id=userID)
            totBids = Bids.objects.filter(listingID=listing)

            # sets messages to show about bids. total and if user has current max bid
            bidsCount = str(totBids.count())
            numBids = bidsCount + " bid(s) so far."
            ownerCheck = ""
            bidMsgCheck = ""

            if listing.userID == user:
                ownerCheck = "set"

            ownedListing = ownerCheck

            if user == listing.currBidBy and totBids.filter(listingID=listing,bidBy=user).exists():
                bidMsgCheck = " Your bid is the current bid."
            bidMsg = bidMsgCheck


            try:
                watchedItemsCounter = watcherList.objects.filter(watchedBy=user).count()
            except:
                watchedItemsCounter= 0

            try:
                #  gets all comments on listing
                listingComments = Comment.objects.filter(listingID=listing)
                listingComments_sorted = listingComments.order_by('-id')
            except:
                listingComments_sorted = ""
            try:
                #  check if listing is on watchlist
                watcheditems = watcherList.objects.get(listID=listing, watchedBy=user)
            except:
                watcheditems = ""  # this assigns null to variable in the event no rows exist

            return render(request, "listings/index.html", {
                "posting": listing, "items": watcheditems, "numBids": numBids,
                "bidMsg": bidMsg, "ownedListing": ownedListing, "currComments":listingComments_sorted,
                "watchedItems":watchedItemsCounter
            })
        else:
            user = User.objects.get(id=userID)
            try:
                watchedItemsCounter = watcherList.objects.filter(watchedBy=user).count()
            except:
                watchedItemsCounter= 0

        return render(request, "listings/index.html", {
                "closedMsg": "THIS LISTING IS NO LONGER AVAILABLE.",
            "watchedItems":watchedItemsCounter
            })

    else:
        user = User.objects.get(id=userID)
        try:
            watchedItemsCounter = watcherList.objects.filter(watchedBy=user).count()
        except:
            watchedItemsCounter= 0

    return render(request, "listings/index.html", {
            "winMsg": "CONGRATULATIONS! YOUR BID WON THIS LISTING!",
            "watchedItems":watchedItemsCounter
        })


#  ADDS ITEM FROM WATCH LIST
@login_required(login_url='/admin')
def addToWatchList(request):
    idNum = request.POST['listingIDwatch']
    # finalID = int(idNum)
    listing = Listing.objects.get(id=idNum)
    watchUser = get_user(request)
    Adduser = User.objects.get(id=listing.userID.id)
    watcherList.objects.create(listID=listing, addedBy=Adduser, watchedBy=watchUser)
    return HttpResponseRedirect(reverse("listings:index", args=(idNum,)))


#  REMOVES ITEM FROM WATCH LIST
@login_required(login_url='/admin')
def DelFromWatchList(request):
    idNum = request.POST['listingIDwatch']
    listing = Listing.objects.get(id=idNum)
    watchUser = get_user(request).id
    Adduser = User.objects.get(id=listing.userID.id)
    watcherList.objects.get(listID=listing, addedBy=Adduser, watchedBy=watchUser).delete()
    return HttpResponseRedirect(reverse("listings:index", args=(idNum,)))


#  CLOSES LISTING
@login_required(login_url='/admin')
def closeListing(request):
    idNum = request.POST['postingID']
    listObject = Listing.objects.get(id=idNum)
    cDate = datetime.now()
    # archives post before deleting.
    hist_lists.objects.create(listingID=idNum, startingBid=listObject.startingBid, finalBid=listObject.bid,
                              finalBidBy=listObject.currBidBy, listBy=listObject.userID,closedDateTime=cDate)
    listObject.delete()
    userID = get_user(request).id
    user = User.objects.get(id=userID)
    try:
        watchedItemsCounter = watcherList.objects.filter(watchedBy=user).count()
    except:
        watchedItemsCounter= 0

    return render(request, "listings/index.html", {
        "closedMsg": "THIS LISTING HAS BEEN CLOSED.",
        "watchedItems":watchedItemsCounter
    })

commerce/listings/templates/listings/index.html
{% extends 'auctions/layout.html' %}


{% block body %}

    {% if closedMsg %} <!--  if page loads and listing is closed then it will show message-->
        <strong>{{ closedMsg }}</strong>
        {% elif winMsg %}
        <strong>{{ winMsg }}</strong>

    {% else %} <!--  If page loads and listing is open it will show listing details-->
        <strong style="font-size: 40px;">Listing: {{ posting.title }}</strong><br><br>

        <!-- WATCHLIST ACTION BUTTON-->
        {% if items %}
            <form action="{% url 'listings:del'%}"  method="post" >
                {% csrf_token %}
                <input type="hidden" value="{{ posting.id }}" name="listingIDwatch">
                <input style="background-color: darkslategray; color: #ffe6ff" type="submit"
                       value="Remove from watchlist">
            </form>
        {% else %}
            <form action="{% url 'listings:add'%}" method="POST" >
                {% csrf_token %}
                <input type="hidden" value="{{ posting.id }}" name="listingIDwatch">
                <input style="background-color: darkslategray; color: #ffe6ff" type="submit"
                       value="Add To Watchlist">
            </form>
        {% endif %}
<br>

        <!-- START OF LISTING DETAILS-->
        <div style="padding-top: 20px;">

            <div style="width: 305px;">
                <!--brings me to listings page with Listing ID#-->
                <a href="{% url 'listings:index'%}{{ posting.id }}">
                    <img style="margin-left:  30px; width: 300px; height:200px;" src="{{ posting.url }}"
                         alt="image could not load"></a>
            </div><br>

            <div>
                <p style="margin-left:  30px;" class="text-muted">{{ posting.description }}</p>
            </div><br>
            <div>  <!-- floatformat:2 sets the decimal places for the value given value-->
                <p style="font-size: 25px;margin-left:  30px;"><b>${{ posting.bid|floatformat:2}}</b></p>
            </div>
            <p>{{ numBids }} {{ bidMsg }}</p> <!-- listing bid messages-->
            <div>

    <!-- PLACE BID FORM-->
                <form method="post" action="{% url 'listings:bid' %}">
                    {% csrf_token %}
                    <input type="text" name="bidAmt" placeholder="Bid">
                    <input type="hidden" value="{{ posting.id }}" name="listingID">

                    {% if messages and not method%}
                        {% for msg in messages %}
                            {% if msg.tags %}
                                <script><!-- to use alerts then the script tags must be used-->
                                alert("{{ msg }}")
                                </script>
                            {% endif %}
                        {% endfor %}
                    {% endif %}

                    <input type="submit" style="background-color: blue; color: white;margin-left: 30px;"
                           value="Place Bid">
                </form>

            </div><br>
            <div>
                <strong style="margin-left:  30px; font-size: 20px;">Details</strong> </div>
            <ul>
                <li> Listed By: {{ posting.userID.username }}</li>
                <li>  Category: {{ posting.category_name }}</li>
            </ul>
        </div>
        <!-- END OF LISTING DETAILS-->

        <!--CLOSE LISTING ACTIONS   -->

        {% if ownedListing %}
            <form action="{% url 'listings:close'%}"  method="post" >
                {% csrf_token %}
                <input type="hidden" value="{{ posting.id }}" name="postingID">
                <input style="background-color: red; color: #ffe6ff" type="submit"
                       value="Close Listing">
            </form><br>
        {% endif %}

        <!-- COMMENTS SECTION-->
        <div class="enterComment" style="color: darkslategray">
            <form method="POST" action="{% url 'listings:comm'%}" >
                {% csrf_token %}
                <input type="hidden" value="{{ posting.id }}" name="postingID">
                <textarea style="width: 650px; height: 65px; resize: none;" name="userComment"
                          placeholder="Enter comment here.."></textarea>
                <input type="submit" style="bottom: 10px; position: relative;
             background-color: blue; color: white" value="Post Comment">
            </form>
        </div>


        <div class="commentsBlock" style=" width:90%; background-color: whitesmoke">
    {% if currComments %}
    {% for comm in currComments %}
        <ul>
            <li style="list-style: none; ">
                <b>{{comm.commentMade}} </b><br>
               <p> - {{ comm.commentBy.username }}</p>
                <p style="position: relative; bottom:40px; left: 60px; margin-left: 10px;"
                   class="text-muted">{{ comm.datetimeOfComment }}</p>
            </li><hr>
        </ul>
    {% endfor %}
        {% endif %}
</div>

    {% endif %}
    <div hidden>
    {% block notifCount %}
        {{ watchedItems }}
    {% endblock %}
    </div>
{% endblock %}