commerce/auctions/urls.py
from django.urls import path

from . import views

app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/categories/urls.py
from django.urls import path

from . import views

app_name = "categories"
urlpatterns = [
    path("", views.Categories, name="index"),
    path("", views.CategoryView, name="catView"),
    path("<str:categoryName>", views.CategoryView, name="catView")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("create/", include("createList.urls")),
    path("categories/", include("categories.urls")),
    path("watchlist/", include("watchlist.urls")),
    path("listings/", include("listings.urls"))
]

commerce/listings/urls.py
from django.urls import path

from . import views
# IT IS IMPORT TO REMEMBER THAT URL WITH ARGUMENTS CAN NEVER BE IDENTICAL. EVEN IF NAME ATTR IS DIFFERENT
app_name = "listings"
urlpatterns = [
    path("", views.listingsView, name="index"),
    path('<int:idNo>', views.listingsView, name="index"),

    path("", views.postComment, name="comm"),
    path("post_comment",views.postComment,name="comm"),

    path("", views.addToWatchList, name="add"),
    path("add_to_list",views.addToWatchList,name="add"),

    path("", views.DelFromWatchList, name="del"),
    path("remove_to_list",views.DelFromWatchList,name="del"),

    path("", views.createBid, name="bid"),
    path("submit_bid",views.createBid,name="bid"),

    path("", views.closeListing, name="close"),
    path("close_listing",views.closeListing,name="close")
]

commerce/categories/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import get_user
from watchlist.models import watcherList
from auctions.models import User
from django.http import HttpResponseRedirect
from createList.models import Category,Listing
# Create your views here.

def Categories(request):
    idNo = get_user(request).id
    user_code = User.objects.get(id=idNo)

    try:
        watchedItemsCounter = watcherList.objects.filter(watchedBy=user_code).count()
    except:
        watchedItemsCounter= 0
    return render(request,"categories/index.html",{
        "cat_list":Category.objects.all(),  "watchedItemsCounter":watchedItemsCounter
    })

def CategoryView(request,categoryName):
    idNo = get_user(request).id
    user_code = User.objects.get(id=idNo)
    try:
        watchedItemsCounter = watcherList.objects.filter(watchedBy=user_code).count()
    except:
        watchedItemsCounter= 0

# this statement searches Category table by NAME but only returns the CODE field.
    cat_code = Category.objects.filter(name=categoryName).values_list('code')

    return render(request,"categories/viewCat.html",{
        "cat":categoryName, "listings":Listing.objects.filter(category_name__in=cat_code),
        "watchedItemsCounter":watchedItemsCounter
        #  __in on the category_name field is used to handle result sets greateer than 1
    })

commerce/categories/templates/categories/index.html
{% extends 'auctions/layout.html' %}


{% block body %}

{% for cat in cat_list %}
    <ul>
    <li>
<a href='{% url "categories:catView"%}{{ cat.name }}'>{{ cat.name}}</a>
    </li>
    </ul>
    {% endfor %}
    <div hidden>
        {% block notifCount %}
            {{ watchedItemsCounter }}
        {% endblock %}
    </div>
{% endblock %}

commerce/categories/templates/categories/viewCat.html
{% extends 'auctions/layout.html' %}

{% block title %}
{{ cat }}
{% endblock %}

{% block body %}

    {% for entry in listings %}

        <hr>
        <table style="background-color:#ffe6ff; width: 100%;">
            <tr>
                <td>
                    <a href="{% url 'listings:index'%}{{ entry.id }}">
                    <img style="margin-left:  30px; margin-left:  30px; width: 300px; height:200px;"
                         src="{{ entry.url }}"
                         alt="image could not load"></a>
                </td>
                <td>
                    <p style="margin-right: 150px;"><b>{{ entry.title }}</b></p><br>
                    <p><b>Price: ${{ entry.bid | floatformat:2 }}</b></p><br>
                    <p>{{ entry.description }}</p>
                </td>
            </tr>
        </table>
    {% empty %}
        <strong>NO LISTINGS</strong>

    {% endfor %}
<br>
    <div hidden>
        {% block notifCount %}
            {{ watchedItemsCounter }}
        {% endblock %}
    </div>
{% endblock %}